version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"  # Puerto del servidor: Puerto del contenedoro

  db:
    image: redis:latest
    container_name: redis_db
    # Este servicio no necesita mapeo de puertos al exterior
